---
- name: 'Verify | gpg extension'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | /home/user_valid_gpg_keys/.gnupg/gpg.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /home/user_valid_gpg_keys/.gnupg/gpg.conf'
        test_file: '/home/user_valid_gpg_keys/.gnupg/gpg.conf'
        test_owner: '800'
        test_group: '800'
        test_mode: '0600'
        test_state: 'file'
        test_diff: true

    - name: 'Verify | query imported key trust'
      ansible.builtin.command: 'gpg --export-ownertrust'
      changed_when: false
      become: true
      become_user: 'user_valid_gpg_keys'
      register: _test_users_gpg_key_list

    - name: 'Verify | assert import trust correct'
      ansible.builtin.assert:
        quiet: true
        that: (_test_users_gpg_key_list.stdout_lines | last | split(":"))[1] == "2"  # yamllint disable-line rule:line-length
        fail_msg: >
          ✘ user_valid_gpg_keys imported trust NOT correct (expected 2).
