---
###############################################################################
# Manage User GnuPG
###############################################################################
# Configure GPG keys for given user account. Assumes GPG keys have been
# pre-generated for deployment. Pre-existing keys are detected using all
# available real name and email data. Trust level is set when importing the
# key.
#
# Manually generate key by setting gpg.conf preferences and:
#
#   gpg --full-gen-key --expert
#   gpg --list-keys --keyid-format LONG
#   gpg --export --armor --output public.key.asc {KEYID}
#   gpg --list-secret-keys --keyid-format LONG
#   gpg --export-secret-keys --armor --output private.key.asc {KEYID}
#
# Current trust levels may be exported for configuration:
#
#   gpg --export-ownertrust
#
# Exported trust levels will be trust level +1 (e.g. 5 -> 6, etc.). Be **sure**
# to adjust these when setting key options.
#
#   1 = I don't know or won't say
#   2 = I do NOT trust
#   3 = I trust marginally
#   4 = I trust fully
#   5 = I trust ultimately
#
# If you configure multiple secret keys, be sure to set 'default-key' in
# gpg.conf.
#
# Args:
#   users__user: dict - user with 'gpg' key set.
#
# Reference:
# * https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration.html
# * https://github.com/drduh/config/blob/master/gpg.conf
# * https://wiki.archlinux.org/title/GnuPG
# * https://www.gnupg.org/documentation/manuals/gnupg/GPG-Esoteric-Options.html

- name: '{{ "Gnupg | filesystem | set " ~ users__user.home ~ "/.gnupg" }}'
  ansible.builtin.file:
    dest: '{{ users__user.home ~ "/.gnupg" }}'
    owner: '{{ users__user.name }}'
    group: '{{ users__user.name }}'
    mode: '0700'
    state: 'directory'

- name: '{{
      "Gnupg | filesystem | set " ~ users__user.home ~ "/.gnupg/gpg.conf"
    }}'
  ansible.builtin.template:
    src: 'gpg/gpg.conf.j2'
    dest: '{{ users__user.home ~ "/.gnupg/gpg.conf" }}'
    owner: '{{ users__user.name }}'
    group: '{{ users__user.name }}'
    mode: '0600'

- name: 'Gnupg | cmd | warm up GPG DB cache'
  ansible.builtin.command:
    argv:
      - 'gpg'
      - '--list-keys'
  changed_when: false
  become: true
  become_user: '{{ users__user.name }}'

- name: '{{
      "Gnupg | filesystem | set " ~  users__user.home ~ "/.gnupg/trust.list"
    }}'
  ansible.builtin.template:
    src: 'gpg/trust.list.j2'
    dest: '{{ users__user.home ~ "/.gnupg/trust.list" }}'
    owner: '{{ users__user.name }}'
    group: '{{ users__user.name }}'
    mode: '0400'

- name: 'Gnupg | import GPG keys'
  ansible.builtin.include_tasks: 'gnupg_import.yml'
  loop: '{{ users__user.extensions.gpg.gpg_keys }}'
  loop_control:
    loop_var: 'key'
  no_log: true  # Private keys.

- name: '{{
      "Gnupg | cmd | import " ~ users__user.home ~ "/.gnupg/trust.list"
    }}'
  ansible.builtin.command:
    argv:
      - 'gpg'
      - '--import-ownertrust'
      - '{{ users__user.home ~ "/.gnupg/trust.list" }}'
  changed_when: false
  become: true
  become_user: '{{ users__user.name }}'

- name: '{{
      "Gnupg | filesystem | remove " ~ users__user.home ~ "/.gnupg/trust.list"
    }}'
  ansible.builtin.file:
    path: '{{ users__user.home ~ "/.gnupg/trust.list" }}'
    state: 'absent'
