---
# yamllint disable rule:line-length
###############################################################################
# Manage Groups
###############################################################################
# Creates a group based on the users_group_{LABEL} variable from host
# inventory. See default/main.yml for group variable details.
#
# Using default(omit) will pass a null value to task, ensuring that specific
# option is disabled when executed.
#
# Role steps are exactly the same. Always change role_account_add.yml when
# making changes here, unless those changes are defaults.
#
# Args:
#   group: str - Group to manage.
#
# Reference:
# * https://docs.ansible.com/ansible/latest/collections/ansible/builtin/group_module.html
# * https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#dynamic-variables
# * https://github.com/ansible/ansible/issues/44261
# yamllint enable rule:line-length

- name: '{{ "Group | create " ~ users__group.name }}'
  when: users__group is defined and users__group | length > 0
  ansible.builtin.group:
    force: '{{ users__group.force | default(false) }}'
    gid: '{{ users__group.gid | default(omit) }}'
    gid_max: '{{ users__group.gid_max | default(omit) }}'
    gid_min: '{{ users__group.gid_min | default(omit) }}'
    local: '{{ users__group.local | default(false) }}'
    name: '{{ users__group.name }}'
    non_unique: '{{ users__group.non_unique | default(false) }}'
    state: 'present'
    system: '{{ users__group.system | default(false) }}'
  vars:
    users__group: '{{
        hostvars[inventory_hostname]["users_group_" ~ group] | default({})
      }}'
