---
- name: 'Install packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ users_role_packages }}'
      - '{{
          users_role_high_entropy_packages
          if users_high_entropy_enable else
          []
        }}'
      - '{{ users_role_ssh_keygen_packages }}'
    apt_package_update_cache: true

- name: 'Remove groups'
  ansible.builtin.group:
    name: '{{ item }}'
    state: 'absent'
  loop: '{{ users_accounts_groups_absent | default([]) }}'

- name: 'Remove users'
  ansible.builtin.user:
    name: '{{ item }}'
    force: false
    remove: false
    state: 'absent'
  loop: '{{ users_accounts_users_absent | default([]) }}'

- name: 'Manage groups'
  ansible.builtin.include_tasks: 'group.yml'
  loop: '{{ users_accounts_groups | default([]) }}'
  loop_control:
    loop_var: 'group'
  no_log: true  # passwords

- name: 'Manage users'
  ansible.builtin.include_tasks: 'user.yml'
  loop: '{{ users_accounts_users | default([]) }}'
  loop_control:
    loop_var: 'user'
  no_log: true  # passwords, GPG keys, SSH keys
