---
# yamllint disable rule:line-length
###############################################################################
# Manage User Account
###############################################################################
# Creates a user based on the users_user_{LABEL} variable from host inventory.
# See default/main.yml for user variable details.
#
# If include_group is true, the same named users_group_{LABEL} will
# automatically be included. This allows a user to be created without needed to
# specify the same group in another users_cfg_ variable.
#
# Using default(omit) will pass a null value to task, ensuring that specific
# option is disabled when executed.
#
# Bookworm migrated SSH user group to '_ssh'. See reference.
#
# Role steps are exactly the same. Always change role_account_add.yml when
# making changes here, unless those changes are defaults.
#
# Args:
#   user: str - User to manage.
#
# Reference:
# * https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
# * https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#dynamic-variables
# * https://github.com/ansible/ansible/issues/44261
# * https://www.ansiblepilot.com/articles/change-user-password-ansible-module-user/
# * https://salsa.debian.org/ssh-team/openssh/-/commit/18da782ebe789d0cf107a550e474ba6352e68911
# yamllint enable rule:line-length

- name: '{{ "User | fact | detect user attributes " ~ user }}'
  ansible.builtin.set_fact:
    users__user:
      '{{ hostvars[inventory_hostname]["users_user_" ~ user] | default({}) }}'
  no_log: true  # Passwords.

- name: 'User | assert | validate GPG extension options'
  when: >
    users__user.extensions is defined and
    users__user.extensions.gpg is defined
  ansible.builtin.assert:
    quiet: true
    that:
      - users__user.home is defined
      - users__user.extensions.gpg is defined
    fail_msg: |

      ✘ Using extended gpg option requires user.home.

- name: 'User | assert | validate lockdown extension options'
  when: >
    users__user.extensions is defined and
    users__user.extensions.lockdown is defined
  ansible.builtin.assert:
    quiet: true
    that:
      - users__user.home is defined
      - users__user.extensions.lockdown is defined
    fail_msg: |

      ✘ Using extended lockdown option requires user.home.

- name: 'User | assert | validate copy data extension options'
  when: >
    users__user.extensions is defined and
    users__user.extensions.copy_data is defined
  ansible.builtin.assert:
    quiet: true
    that:
      - users__user.home is defined
      - users__user.extensions.copy_data is defined
    fail_msg: |

      ✘ Using extended copy_data option requires user.home.

- name: 'User | assert | validate include group extension options'
  when: >
    users__user.extensions is defined and
    users__user.extensions.include_group is defined
  ansible.builtin.assert:
    quiet: true
    that:
      - users__user.group is defined
      - users__user.extensions.include_group is defined
    fail_msg: |

      ✘ Using extended include_group option requires user.group.

- name: 'User | assert | validate SSH extension options'
  when: >
    users__user.extensions is defined and
    users__user.extensions.ssh is defined
  ansible.builtin.assert:
    quiet: true
    that:
      - users__user.home is defined
      - users__user.group is defined
      - users__user.name is defined
    fail_msg: |

      ✘ Using extended SSH options requires user.{home, group, name}.

- name: 'User | automatically including user group'
  when: >
    users__user.extensions is defined and
    users__user.extensions.include_group is defined and
    users__user.extensions.include_group | bool
  ansible.builtin.include_tasks: 'group.yml'
  vars:
    group: '{{ users__user.name }}'
  no_log: true  # Passwords, gpg keys, ssh keys.

- name: '{{ "User | create " ~ users__user.name }}'
  ansible.builtin.user:
    append: '{{ users__user.append | default(false) }}'
    authorization: '{{ users__user.authorization | default(omit) }}'
    comment: '{{ users__user.comment | default(omit) }}'
    create_home: '{{ users__user.create_home | default(true) }}'
    expires: '{{ users__user.expires | default(-1) }}'
    force: '{{ users__user.force | default(false) }}'
    generate_ssh_key: '{{ users__user.generate_ssh_key | default(false) }}'
    group: '{{ users__user.group | default(omit) }}'
    groups: '{{ users__user.groups | default(omit) }}'
    hidden: '{{ users__user.hidden | default(omit) }}'
    home: '{{ users__user.home | default(omit) }}'
    local: '{{ users__user.local | default(false) }}'
    login_class: '{{ users__user.login_class | default(omit) }}'
    move_home: '{{ users__user.move_home | default(false) }}'
    name: '{{ users__user.name }}'
    non_unique: '{{ users__user.non_unique | default(false) }}'
    password: '{{ users__user.password | default("!") }}'
    password_expire_account_disable:
      '{{ users__user.password_expire_account_disable | default(omit) }}'
    password_expire_max:
      '{{ users__user.password_expire_max | default(omit) }}'
    password_expire_min:
      '{{ users__user.password_expire_min | default(omit) }}'
    password_expire_warn:
      '{{ users__user.password_expire_warn | default(omit) }}'
    password_lock: '{{ users__user.password_lock | default(false) }}'
    profile: '{{ users__user.profile | default(omit) }}'
    remove: '{{ users__user.remove | default(false) }}'
    role: '{{ users__user.role | default(omit) }}'
    seuser: '{{ users__user.seuser | default(omit) }}'
    shell: '{{ users__user.shell | default("/bin/bash") }}'
    skeleton: '{{ users__user.skeleton | default(omit) }}'
    ssh_key_bits: '{{ users__user.ssh_key_bits | default(omit) }}'
    ssh_key_comment:
      '{{ users__user.ssh_key_comment | default("ansible-generated") }}'
    ssh_key_file: '{{ users__user.ssh_key_file | default(".ssh/id_rsa") }}'
    ssh_key_passphrase: '{{
        users__user.ssh_key_passphrase |
        default(lookup("ansible.builtin.password",
                       "/dev/null",
                       chars=["ascii_letters", "digits"],
                       length=32))
      }}'
    ssh_key_type: '{{ users__user.ssh_key_type | default("rsa") }}'
    state: 'present'
    system: '{{ users__user.system | default(false) }}'
    uid: '{{ users__user.uid | default(omit) }}'
    uid_max: '{{ users__user.uid_max | default(omit) }}'
    uid_min: '{{ users__user.uid_min | default(omit) }}'
    umask: '{{ users__user.umask | default(omit) }}'
    update_password: '{{ users__user.update_password | default("always") }}'

- name: 'User | process extensions'
  when: users__user.extensions is defined
  block:
    - name: 'User | apply extended SSH configuration'
      when: users__user.extensions.ssh is defined
      block:
        - name: 'User | filesystem | secure ~/.ssh'
          ansible.builtin.file:
            path: '{{ users__user.home ~ "/.ssh" }}'
            owner: '{{ users__user.name }}'
            group: '{{ users__user.group }}'
            mode: '0700'
            state: 'directory'

        - name: 'User | authorized_key | add'
          when: users__user.extensions.ssh.authorized_keys is defined
          ansible.posix.authorized_key:
            comment: '{{ item.comment | default(omit) }}'
            exclusive: '{{ item.exclusive | default(false) }}'
            follow: '{{ item.follow | default(false) }}'
            key: '{{ item.key }}'
            key_options: '{{ item.key_options | default(omit) }}'
            manage_dir: '{{ item.manage_dir | default(true) }}'
            path: '{{ item.path | default(omit) }}'
            state: '{{ item.state | default("present") }}'
            user: '{{ users__user.name }}'
            validate_certs: '{{ item.validate_certs | default(true) }}'
          loop: '{{ users__user.extensions.ssh.authorized_keys }}'

        # Keep inline instead of include_tasks loop for singular role import.
        - name: 'User | manage SSH keys'
          when: users__user.extensions.ssh.ssh_keys is defined
          block:
            - name: 'User | filesystem | add private keys ~/.ssh/'
              when: item.state | default("present") == 'present'
              ansible.builtin.copy:
                dest: '{{
                    users__user.home ~ "/.ssh/" ~ item.name | default("id_rsa")
                  }}'
                owner: '{{ users__user.name }}'
                group: '{{ users__user.group }}'
                mode: '0400'
                content: '{{ item.private }}'
              loop: '{{ users__user.extensions.ssh.ssh_keys }}'
              no_log: true  # Private key.

            - name: 'User | filesystem | add public keys ~/.ssh/'
              when: item.state | default("present") == 'present'
              ansible.builtin.copy:
                dest: '{{
                    users__user.home ~ "/.ssh/" ~
                    item.name | default("id_rsa") ~ ".pub"
                  }}'
                owner: '{{ users__user.name }}'
                group: '{{ users__user.group }}'
                mode: '0640'  # Prevent file thrashing if lockdown is set.
                content: '{{ item.public }}'
              loop: '{{ users__user.extensions.ssh.ssh_keys }}'
              no_log: true  # Private key.

            - name: 'User | filesystem | remove private keys ~/.ssh/'
              when: item.state | default("present") == 'absent'
              ansible.builtin.file:
                path: '{{
                    users__user.home ~ "/.ssh/" ~ item.name | default("id_rsa")
                  }}'
                state: 'absent'
              loop: '{{ users__user.extensions.ssh.ssh_keys }}'
              no_log: true  # Private key.

            - name: 'User | filesystem | remove public keys ~/.ssh/'
              when: item.state | default("present") == 'absent'
              ansible.builtin.file:
                path: '{{
                    users__user.home ~ "/.ssh/" ~
                    item.name | default("id_rsa") ~ ".pub"
                  }}'
                state: 'absent'
              loop: '{{ users__user.extensions.ssh.ssh_keys }}'
              no_log: true  # Private key.

        - name: 'User | filesystem | set ~/.ssh/config'
          when: users__user.extensions.ssh.config is defined
          ansible.builtin.template:
            src: 'ssh/config.j2'
            dest: '{{ users__user.home ~ "/.ssh/config" }}'
            owner: '{{ users__user.name }}'
            group: '{{ users__user.group }}'
            mode: '0400'

    - name: 'User | sudoers | set'
      when: users__user.extensions.sudoers is defined
      community.general.sudoers:
        commands:
          '{{ users__user.extensions.sudoers.commands | default(omit) }}'
        group: '{{ users__user.extensions.sudoers.group | default(omit) }}'
        host: '{{ users__user.extensions.sudoers.host | default("ALL") }}'
        name: '{{ users__user.extensions.sudoers.name }}'
        noexec: '{{ users__user.extensions.sudoers.noexec | default(false) }}'
        nopassword:
          '{{ users__user.extensions.sudoers.nopassword | default(true) }}'
        runas: '{{ users__user.extensions.sudoers.runas | default(omit) }}'
        setenv: '{{ users__user.extensions.sudoers.setenv | default(false) }}'
        state:
          '{{ users__user.extensions.sudoers.state | default("present") }}'
        sudoers_path: '{{
            users__user.extensions.sudoers.sudoers_path |
            default("/etc/sudoers.d")
          }}'
        user: '{{ users__user.extensions.sudoers.user | default(omit) }}'
        validation:
          '{{ users__user.extensions.sudoers.validation | default("detect") }}'

    - name: 'User | configure gnupg'
      when: >
        users__user.extensions.gpg is defined and
        users__user.extensions.gpg | length > 0
      ansible.builtin.include_tasks: 'gnupg.yml'

    - name: 'User | filesystem | copy user data ~'
      when: >
        users__user.extensions.copy_data is defined and
        users__user.extensions.copy_data | length > 0
      ansible.builtin.copy:
        src: '{{ users__user.extensions.copy_data }}'
        dest: '{{ users__user.home }}'
        owner: '{{ users__user.name }}'
        group: '{{ users__user.name }}'
        force: true
        mode: '0600'
        directory_mode: '0700'

    - name: 'User | cmd | lockdown ~'
      when: >
        users__user.extensions.lockdown is defined and
        users__user.extensions.lockdown | bool
      ansible.builtin.command: '{{ "chmod -R go-rwx " ~ users__user.home }}'
      changed_when: false
