---
# Idempotent testing disabled as specific commands will never be idempotent.
#
# Reference:
# * https://github.com/ansible/molecule/issues/816

- name: 'User sudoers extension | converge'
  hosts: all
  gather_facts: true
  tags: 'molecule-idempotence-notest'
  tasks:
    - name: 'User sudoers extension | converge | create test users and groups'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.users'
      vars:
        users_accounts_users:
          - 'sudoers_extension'
