---
# yamllint disable rule:line-length
- name: 'Role account add | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Role account add | prepare | base packages for bare-metal equivalency'
      ansible.builtin.apt:
        name:
          - 'openssh-server'  # ansible.builtin.user (ssh-keygen)
        update_cache: true
        state: 'present'
