---
- name: 'Default | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | prepare | base packages for bare-metal equivalency'
      ansible.builtin.apt:
        name:
          - 'openssh-server'  # ssh-keygen use in ansible.builtin.user.
        update_cache: true
        state: 'present'
