---
- name: 'User sudoers extension | converge'
  hosts: 'users-debian-12-sudoers_extension-user'
  gather_facts: false
  tasks:
    - name: 'User sudoers extension | converge | apply r_pufky.srv.users (user)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.users'

- name: 'User sudoers extension | converge'
  hosts: 'users-debian-12-sudoers_extension-role'
  gather_facts: false
  tasks:
    - name: 'User sudoers extension | converge | apply r_pufky.srv.users (role)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.users'
        tasks_from: 'role_account_add.yml'
