---
- name: 'Converge'
  hosts: 'users-debian-12-sudoers_extension-user'
  gather_facts: false
  tasks:
    - name:
        'Converge | apply r_pufky.deb.users (user)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.users'

- name: 'Converge'
  hosts: 'users-debian-12-sudoers_extension-role'
  gather_facts: false
  tasks:
    - name:
        'Converge | apply r_pufky.deb.users (role)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.users'
        tasks_from: 'role_account_add.yml'
