---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | /etc/sudoers.d/sudoers_extension'
      ansible.builtin.slurp:
        path: '/etc/sudoers.d/sudoers_extension'
      register: _test_users_sudoers_extension

    - name: 'Verify | assert sudoers configuration correct'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_users_sudoers_extension.content | b64decode == '%sudo ALL=(root)NOEXEC:SETENV: ALL'  # yamllint disable-line rule:line-length
        fail_msg: >
          ✘ sudoers_extension sudoers invalid
          (expected %sudo ALL=(root)NOEXEC:SETENV: ALL).
