---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | test | /etc/sudoers.d/sudoers_extension'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | test | /etc/sudoers.d/sudoers_extension'
        test_src: 'files/sudoers_extension'
        test_file: '/etc/sudoers.d/sudoers_extension'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0440'
        test_state: 'file'
        test_diff: true
