---
# yamllint disable rule:line-length
###############################################################################
# Default User Dependencies
###############################################################################
#
# Reference:
# * https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user

# Last time user options were validated against a default configuration.
users_role_validate_date: '2024-06-23'
users_role_validate_release: 'bookworm'

# Default packages for users.
users_role_packages:
  - 'gnupg2'
  - 'acl'  # unprivileged user GPG (gnupg2) setup

# Packages to apply to ALL containers.
#
# containers are detected via ansible_virtualization_role.
users_role_container_gnupg_packages:
  - 'rng-tools5'  # https://packages.debian.org/bookworm/rng-tools5
  - 'haveged'  # https://packages.debian.org/bookworm/haveged

# Packages to apply to ALL virtual machines.
# Virtual machines are detected via ansible_virtualization_role.
#
# Default: See below.
users_role_vm_gnupg_packages:
  - 'haveged'  # https://packages.debian.org/bookworm/haveged

# Default state for apt package installation. See ansible.builtin.apt.
users_role_package_state: 'latest'

###############################################################################
# Password Hash Defaults
###############################################################################
# Defaults for each algorithm for hashing passwords.
#
# All systems should be using sha512 or bcrypt.
#
# Reference:
# * https://man7.org/linux/man-pages/man3/crypt.3.html
# * https://docs.ansible.com/ansible/devel/collections/ansible/builtin/password_hash_filter.html
# * https://github.com/ansible/ansible/blob/d0b6ce7473e1ca475b6a3e9334426063a4d189f7/lib/ansible/utils/encrypt.py#L77

users_role_password_algo_constraints:
  md5: {id: '1', salt_length: 8, rounds: '', salt_exact: false, ident: ''}
  bcrypt: {id: '2b', salt_length: 22, rounds: 12, salt_exact: true, ident: '2b'}
  sha256: {id: '5', salt_length: 16, rounds: 535000, salt_exact: false, ident: ''}
  sha512: {id: '6', salt_length: 16, rounds: 656000, salt_exact: false, ident: ''}
