---
- name: 'User SSH extension | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'User SSH extension | converge | apply r_pufky.srv.users'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.users'
