---
- name: 'Default | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | converge | apply r_pufky.srv.users'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.users'
