---
# yamllint disable rule:line-length
# As these are encapsulated ansible tasks just ensure that sending all options
# successfully executes, as well as toggling user and group.
- name: 'Default | verify | extraction successful'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verfiy | query user_all_defaults_valid'
      ansible.builtin.getent:
        database: 'passwd'
        key: 'user_all_defaults_valid'

    - name: 'Default | verify | assert user_all_defaults_valid created'
      ansible.builtin.assert:
        that:
          - '"user_all_defaults_valid" in ansible_facts.getent_passwd'
          - ansible_facts.getent_passwd.user_all_defaults_valid[1] == '1000'
          - ansible_facts.getent_passwd.user_all_defaults_valid[2] == '1000'
          - ansible_facts.getent_passwd.user_all_defaults_valid[4] == '/nonexistent'
          - ansible_facts.getent_passwd.user_all_defaults_valid[5] == '/usr/sbin/nologin'
        success_msg: 'user_all_defaults_valid correct.'
        fail_msg: 'user_all_defaults_valid incorrect passwd values.'

    - name: 'Default | verfiy | query group_all_defaults_valid'
      ansible.builtin.getent:
        database: 'group'
        key: 'group_all_defaults_valid'

    - name: 'Default | verify | assert group created'
      ansible.builtin.assert:
        that:
          - '"group_all_defaults_valid" in ansible_facts.getent_group'
          - ansible_facts.getent_group.group_all_defaults_valid[1] == '1001'
        success_msg: 'group_all_defaults_valid correct.'
        fail_msg: 'group_all_defaults_valid incorrect passwd values.'

    - name: 'Default | verfiy | query group_all_specified_values'
      ansible.builtin.getent:
        database: 'group'
        key: 'group_all_specified_values'

    - name: 'Default | verify | assert group created'
      ansible.builtin.assert:
        that:
          - '"group_all_specified_values" in ansible_facts.getent_group'
          - ansible_facts.getent_group.group_all_specified_values[1] == '1500'
        success_msg: 'group_all_specified_values correct.'
        fail_msg: 'group_all_specified_values incorrect passwd values.'

    - name: 'Default | verfiy | query user_all_specified_values'
      ansible.builtin.getent:
        database: 'passwd'
        key: 'user_all_specified_values'

    - name: 'Default | verify | assert user_all_specified_values created'
      ansible.builtin.assert:
        that:
          - '"user_all_specified_values" in ansible_facts.getent_passwd'
          - ansible_facts.getent_passwd.user_all_specified_values[1] == '1500'
          - ansible_facts.getent_passwd.user_all_specified_values[2] == '1500'
          - ansible_facts.getent_passwd.user_all_specified_values[3] == '(logins disabled)'
          - ansible_facts.getent_passwd.user_all_specified_values[4] == '/etc/test_location'
          - ansible_facts.getent_passwd.user_all_specified_values[5] == '/bin/bash'
        success_msg: 'user_all_specified_values correct.'
        fail_msg: 'user_all_specified_values incorrect passwd values.'

    - name: 'Default | verfiy | query user_simul_user'
      ansible.builtin.getent:
        database: 'passwd'
        key: 'user_simul_user'

    - name: 'Default | verfiy | query user_simul_group'
      ansible.builtin.getent:
        database: 'group'
        key: 'user_simul_group'

    - name: 'Default | verify | assert group created'
      ansible.builtin.assert:
        that:
          - '"user_simul_group" in ansible_facts.getent_group'
          - ansible_facts.getent_group.user_simul_group[1] == '1550'
        success_msg: 'user_simul_group correct.'
        fail_msg: 'user_simul_group incorrect passwd values.'

    - name: 'Default | verify | assert user_simul_user created'
      ansible.builtin.assert:
        that:
          - '"user_simul_user" in ansible_facts.getent_passwd'
          - ansible_facts.getent_passwd.user_simul_user[1] == '1550'
          - ansible_facts.getent_passwd.user_simul_user[2] == '1551'
        success_msg: 'user_simul_user correct.'
        fail_msg: 'user_simul_user incorrect passwd values.'
