---
# Verify copy_data extension works properly.
dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        users_accounts_users:
          - 'user_copy_data'
        users_group_user_copy_data:
          name: 'user_copy_data'
          gid: 800
        users_user_user_copy_data:
          name: 'user_copy_data'
          group: 'user_copy_data'
          home: '/home/user_copy_data'
          uid: 800
          extensions:
            include_group: true
            copy_data: 'files/copy_data'
platforms:
  - name: 'users-debian-12-user_copy_data_extension'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    # - 'idempotence'  # User accounts are only created once.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
